components:
  schemas:
    Address:
      properties:
        Identification:
          items: {description: 'A unique identifier for this trade address.', type: string }
          type: array
        Type:
          items: {description: 'A code specifying the type of this trade address, such as business address or home address.', type: string }
          type: array
        LineOne:
          description: 'The first free form line, expressed as text, of this trade address.'
          type: string
        LineTwo:
          description: 'The second free form line, expressed as text, of this trade address.'
          type: string
        LineThree:
          description: 'The third free form line, expressed as text, of this trade address.'
          type: string
        LineFour:
          description: 'The fourth free form line, expressed as text, of this trade address.'
          type: string
        CityName:
          description: 'The name, expressed as text, of the city, town or village of this trade address.'
          type: string
        Postcode:
          description: 'A code specifying the postcode of this trade address.'
          type: string
        CountrySubDivisionName:
          description: 'A name, expressed as text, of the sub-division of a country for this trade address.'
          type: string
        Country:
          description: 'The unique identifier of a country for this trade address.'
          type: string
    CommercialInvoice:
      properties: {}
      allOf:
        - $ref: '#/components/schemas/Document'
        - type: object
    Consignment:
      properties:
        Identification:
          description: 'A unique identifier for this supply chain consignment.'
          type: string
        SummaryDescription:
          description: 'A textual summary description of this supply chain consignment.'
          type: string
        ExportCountry:
          description: 'missing description'
          type: string
        ImportCountry:
          description: 'missing description'
          type: string
        ConsignmentItem:
          items: {$ref: '#/components/schemas/ConsignmentItem'}
          type: array
        ConsignmentLocation:
          properties:
            Role:
              description: 'missing description'
              type: string
              enum: [CarrierAcceptance,ConsigneeReceipt,DeclaredForCustoms,FinalDestination,LoadingBaseport,Loading,Transit,Transshipment,Unloading,UnloadingBaseport]
            Identification:
              description: 'A unique identifier for this logistics related location, such as a United Nations Location Code (UNLOCODE) or GS1 Global Location Number (GLN).'
              type: string
            Name:
              description: 'A name, expressed as text, of this logistics related location.'
              type: string
      required: [ExportCountry,ImportCountry]
    ConsignmentItem:
      properties:
        Identification:
          items: {description: 'A unique identifier for this supply chain consignment item.', type: string }
          type: array
        Sequence:
          description: 'The sequence number for this supply chain consignment item.'
          type: number
        DeclaredValueForCustoms:
          description: 'The monetary value of this supply chain consignment item as declared for customs purposes.'
          type: string
        GrossVolume:
          description: 'A measure of the gross volume, normally calculated by multiplying the maximum length, width and height of this supply chain consignment item.'
          type: string
        GrossWeight:
          description: 'A measure of the gross weight (mass) of this supply chain consignment item which includes packaging but excludes any transport equipment.'
          type: string
        Information:
          items: {description: 'Information, expressed as text, for this supply chain consignment item.', type: string }
          type: array
        Package:
          description: 'The package quantity for this supply chain consignment item.'
          type: string
        PackageType:
          items: {description: 'A package type, expressed as text, for this supply chain consignment item.', type: string }
          type: array
        Tariff:
          description: 'The tariff quantity in this supply chain consignment item.'
          type: string
        Type:
          description: 'The code specifying the type of supply chain consignment item.'
          type: string
        RelatedInvoice:
          properties:
    COO:
      properties:
        Consignment:
          items: {$ref: '#/components/schemas/Consignment'}
          type: array
        OriginRule:
          properties:
            OriginCriterion:
              description: 'missing description'
              type: string
            Identification:
              description: 'A unique identifier for this supply chain consignment item.'
              type: string
            Sequence:
              description: 'The sequence number for this supply chain consignment item.'
              type: number
      allOf:
        - $ref: '#/components/schemas/Document'
        - type: object
    Document:
      properties:
        Identification:
          description: 'The unique identifier of this exchanged document.'
          type: string
        Name:
          description: 'A name, expressed as text, of this exchanged document.'
          type: string
        Description:
          description: 'A textual description of this exchanged document.'
          type: string
        Language:
          items: {description: 'A unique identifier for a language used in this exchanged document.', type: string }
          type: array
        Status:
          description: 'The code specifying the status of this exchanged document.'
          type: string
        Submission:
          description: 'The date, time, date time or other date time value for the formal submission of this exchanged document to a receiver by a sender.'
          type: string
        DocumentParty:
          properties:
            Role:
              description: 'missing description'
              type: string
            Identification:
              description: 'A unique identifier of this trade party.'
              type: string
            Name:
              description: 'The name, expressed as text, for this trade party.'
              type: string
    Location:
      properties:
        Identification:
          description: 'A unique identifier for this logistics related location, such as a United Nations Location Code (UNLOCODE) or GS1 Global Location Number (GLN).'
          type: string
        Name:
          description: 'A name, expressed as text, of this logistics related location.'
          type: string
        Country:
          description: 'The unique identifier of a country for this logistics location.'
          type: string
        Description:
          description: 'A textual description of this logistics related location.'
          type: string
    OriginRule:
      properties:
        OriginCriterion:
          description: 'missing description'
          type: string
      required: [OriginCriterion]
    Party:
      properties:
        Identification:
          items: {description: 'A unique identifier of this trade party.', type: string }
          type: array
        Name:
          description: 'The name, expressed as text, for this trade party.'
          type: string
        Description:
          items: {description: 'A textual description of this trade party.', type: string }
          type: array
        Language:
          description: 'A code specifying a language for this trade party.'
          type: string
        Type:
          items: {description: 'A code specifying the type of trade party that is independent of its role.', type: string }
          type: array
        Address: {$ref: '#/components/schemas/Address'}
    TransportEvent:
      properties:
        Description:
          description: 'The textual description of this transport event.'
          type: string
        Occurrence:
          description: 'The scheduled date, time, date time, or other date time value of the occurrence of this transport event.'
          type: string
        Type:
          description: 'The code specifying the type of transport event.'
          type: string
          enum: [Call,Arrival,Departure,Loading,UnLoading,BorderCrossing,TransShipment,Stop]
        EventLocation:
          properties:
            Identification:
              description: 'A unique identifier for this logistics related location, such as a United Nations Location Code (UNLOCODE) or GS1 Global Location Number (GLN).'
              type: string
            Name:
              description: 'A name, expressed as text, of this logistics related location.'
              type: string
    TransportMeans:
      properties:
        Identification:
          items: {description: 'An identifier of this logistics means of transport, such as the International Maritime Organization number of a vessel.', type: string }
          type: array
        Name:
          description: 'The name, expressed as text, of this logistics means of transport.'
          type: string
        Type:
          description: 'The code specifying the type of logistics means of transport (Reference UNECE Recommendation 28).'
          type: string
        TransportMeansParty:
          properties:
            Role:
              description: 'missing description'
              type: string
              enum: [ServiceProvider,Owner,OwnerAgent,Operator,ISSCIssuingAuthority]
            Identification:
              description: 'A unique identifier of this trade party.'
              type: string
            Name:
              description: 'The name, expressed as text, for this trade party.'
              type: string
    TransportMovement:
      properties:
        Identification:
          description: 'The unique identifier for this logistics transport movement, such as a voyage number, flight number, or trip number.'
          type: string
        Information:
          description: 'Information, expressed as text, for this logistics transport movement.'
          type: string
        Mode:
          description: 'The code specifying the mode, such as by air, sea, rail, road or inland waterway, for this logistics transport movement.'
          type: string
        Status:
          description: 'The code specifying a status for the logistics transport movement, such as estimated or final.'
          type: string
        Type:
          description: 'The type, as expressed as text, of the logistics transport movement.'
          type: string
          enum: [OnCarriage,PreCarriage,MainCarriage,BorderCrossing,AtArrival,AtDeparture]
        UsedTransportMeans:
          properties:
            Identification:
              description: 'An identifier of this logistics means of transport, such as the International Maritime Organization number of a vessel.'
              type: string
            Name:
              description: 'The name, expressed as text, of this logistics means of transport.'
              type: string
        Scheduled:
          items: {$ref: '#/components/schemas/TransportEvent'}
          type: array
        Estimated:
          items: {$ref: '#/components/schemas/TransportEvent'}
          type: array
        Actual:
          items: {$ref: '#/components/schemas/TransportEvent'}
          type: array
        TransportMovementParty:
          properties:
            Role:
              description: 'missing description'
              type: string
              enum: [Carrier,NVOCC,ConsortiumCarrier,CarrierAgent,Inspection,UnloadingInspection,LoadingInspection,TerminalOperator,Stevedore,ConsolidatorAgent,Notified,SailingAdviceNotified,DocumentaryInstructions,CommodityConsolidator,CommodityConsolidatorAgent]
            Identification:
              description: 'A unique identifier of this trade party.'
              type: string
            Name:
              description: 'The name, expressed as text, for this trade party.'
              type: string
info: {description: CertificateOfOrigin API - 1.0.0, title: CertificateOfOrigin API, version: '1.0.0'}
openapi: 3.0.0
paths:
  /CertificatesOfOrigin:
    post:
      tags:
        - CertificatesOfOrigin
      description:  Create a new COO
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/COO'}
        description: ''
        required: true
      responses:
        '201':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/COO'}
          description: Created
    get:
      tags:
        - CertificatesOfOrigin
      description: Get a list of COO
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {$ref: '#/components/schemas/COO'}
                type: array
          description: OK
  /CertificatesOfOrigin/{id}:
    get:
      tags:
        - CertificatesOfOrigin
      description: Get single COO by id
      parameters:
      - description: missing description
        in: path
        name: id
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/COO'}
          description: OK
servers: []